### PR TITLE
Get account holder basic info

### PR DESCRIPTION
**Pull request by alhaji-aki**
Users can the basic info of account holders

### CODE REVIEW

**Comment by mtvbrianking** [comment]
@alhaji-aki can you point me to this endpoint in the MTN docs.

A url to where it's documented...

**Comment by stevebaros** [comment]
Does this apply to all  countries where MTN MOMO works ? .

**Comment by mtvbrianking** [comment]
> Does this apply to all countries where MTN MOMO works ? .

I'm not sure.

But I can see they've added a few more endpoints to the API

**Comment by mtvbrianking** [comment]
@alhaji-aki I've seen the endpoint.

https://momodeveloper.mtn.com/docs/services/collection/operations/basicuserInfo-GET

Over the weekend, I'll move CI to Github actions (from TravisCI)  so that we're able to merge the pull requests.

**Comment by alhaji-aki** [comment]
> @alhaji-aki I've seen the endpoint.
> 
> https://momodeveloper.mtn.com/docs/services/collection/operations/basicuserInfo-GET
> 
> Over the weekend, I'll move CI to Github actions (from TravisCI) so that we're able to merge the pull requests.

Thank you.

**Comment by mtvbrianking** [comment]
> Thank you. I see I messed up some little part of styleci. I tried fixing them but vs code wont allow me.

I'll fix the code style.

The package uses [`php-cs-fixer`](https://github.com/FriendsOfPHP/PHP-CS-Fixer) for the code style.

**Comment by alhaji-aki** [comment]
Oh ok...

**Comment by alhaji-aki** [comment]
version 4.0.0 does not not include this merge. Do I need to pull the master branch before I can get this merge?

**Comment by mtvbrianking** [comment]
> version 4.0.0 does not not include this merge. Do I need to pull the master branch before I can get this merge?

https://github.com/mtvbrianking/laravel-mtn-momo/releases/tag/v4.1.0

**Pull request merged**
